### PR TITLE
Updated core, added quiet mode and kWh

### PR DESCRIPTION
**Pull request by RobertJansen1**
Together with Bill-Dung, we upgraded the MHI core files, added fan modes and implemented kWh energy used sensor

### CODE REVIEW

**Comment by SomeSander** [comment]
Awesome,, this esphome version in combination with core files is working great for a long time already. Happy to see these improvements!

**Comment by ginkage** [comment]
Wow, nice. Thank you!

**Comment by nbeernink** [comment]
@RobertJansen1 Thank you very much for your efforts!

One question: You reference 2.7R4, is this a typo and did you mean 2.6R4? I don't see it here: https://github.com/absalom-muc/MHI-AC-Ctrl/releases

**Comment by RobertJansen1** [comment]
it is 2.7R4, it is not released yet: https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Version.md

**Pull request merged**
