### PR TITLE
Convert project to external ESPHome component

### PR DESCRIPTION
**Pull request by XMaarten**
This change makes it possible to load the code within ESPHome as an external component, and solves #55.

### CODE REVIEW

**Comment by RobertJansen1** [comment]
Thanks for figuring this out and pushing it! i think we still need to make an example yaml file which does the pulling in the right order, putting the git stuff in the large_framesize and legacy_framesize yaml's feels like the wrong location, as a user now still has to pull all files or merge the stuff himself as the lr_mhi_ac_ac_ctrl.yaml is the "main" file. i am trying this out now and see how far i can get :)

**Comment by XMaarten** [comment]
Ah, sorry about that, you are right, it should be in the lr_mhi_ac_ac_ctrl.yaml file. I didn't investigate the reason for the large and legacy framesize yaml files, and just put combined some things within the ESPHome configuration and it worked for me. I assumed it was only a different initial_value between them too, but I see now that there are more changes between the files. I would move lr_mhi_ac_ac_ctrl.yaml to the conf directory as well, and explain things in the readme.

**Comment by XMaarten** [comment]
If you want to keep the " !include conf/large_framesize.yaml" within the yaml, the directory should probably be moved insides the "components/MHI-AC-Ctrl" directory to work properly. lr_mhi_ac_ac_ctrl.yaml should be in the root and renamed to example_MHI-AC-Ctrl-ESPHhome.yaml according to the [docs](https://esphome.io/components/external_components.html).

**Comment by RobertJansen1** [comment]
yes, i am trying that but it seems either i am doing it wrong, or i just don't understand it, i am getting some compile errors :)

as the includes are still in the lr_mhi_ac_ac_ctrl.yaml i _think_ the custom component was not loaded yet (it gives me some errors about the naming of the vars with the dashes for example) i am checking it out

**Comment by XMaarten** [comment]
Does it work if you paste the contents of the yaml file within ESPHome like I did?

**Comment by RobertJansen1** [comment]
no that doesn't work for me, but to be honest, i think it worked because the includes were still in the main yaml, and so it was not using the external components part of the new files in the sub-yaml's. i am debugging the stuff in my own fork to see if i can get it to work.

**Comment by XMaarten** [comment]
I am very sorry, but I think you are right. I tried with a fresh ESPHome docker install and am getting errors now as well

**Comment by XMaarten** [comment]
Sorry, this isn't working as I thought it would

**Comment by RobertJansen1** [comment]
no worries, it gave me the needed motivation to pick this up further. i finally got it to compile and install on the ESP, but nothing works, so that's a start :)

**Pull request closed without merging**
