### PR TITLE
Update lambda to fix build

### PR DESCRIPTION
**Pull request by OperKH**

### CODE REVIEW

**Comment by ginkage** [comment]
This makes little sense: you create three different instances of MhiAcCtrl, whereas there should be only one.

**Comment by ginkage** [comment]
On a related note: what compile error you're getting, and on which ESPHome version?
I'm asking this because I don't get any errors on the latest ESPHome 1.19.4, so I'm not quite sure what this fix is for.

**Comment by OperKH** [comment]
@ginkage I have this error on ESPHome 1.19.4

**Comment by ginkage** [comment]
Could you please give me the detailed output, the exact error, and if possible, your full .yaml file?

**Pull request closed without merging**
