### PR TITLE
Add vanes LR/UD from upstream

### PR DESCRIPTION
**Pull request by RobertJansen1**
From absalom-muc, new fan modes were added (Left/Right and 3Dauto). i updated the code, and added esphome yaml to have vanes LR work, have vanes UD work properly, and have the climate component work as well. an additional button was added for enabling / disabling 3Dauto

https://github.com/absalom-muc/MHI-AC-Ctrl/commit/6d747e1af37ba65575c1816809d378fb89beb7ef

### CODE REVIEW

**Comment by ervee** [comment]
I implemented and tested all files from Robert's Git just yesterday evening and it compiled and installed without issues on one of my ACs. Tested vanes LR/UD and works great. It is hard to validate 3D auto functionality but it looks okay so far. Thank you Robert.

**Comment by RobertJansen1** [comment]
> Tested vanes LR/UD and works great. It is hard to validate 3D auto functionality but it looks okay so far. Thank you Robert.

I updated some more this morning, and installed it on 4 units myself. it is probably worth updating for better climate integration :)

**Comment by ervee** [comment]
Will do that. Are these updates included in this pull?

**Comment by glsf91** [comment]
> It is hard to validate 3D auto functionality

You can see this easily because the vanes up/down will switch position. And the vanes LR will move continuously very slow.

**Comment by ervee** [comment]
> > Tested vanes LR/UD and works great. It is hard to validate 3D auto functionality but it looks okay so far. Thank you Robert.
> 
> I updated some more this morning, and installed it on 4 units myself. it is probably worth updating for better climate integration :)

Installed without issues on my 2 units!

**Comment by JoepWi** [comment]
For one of my MHI units I want to be able to have the airstream facing down and only going left and right. I was nog able to figure this out with the command 'service: esphome.mhi_gang_set_vanes'.
Can somebody tell me the right number codes for the above service?

**Comment by RobertJansen1** [comment]
> For one of my MHI units I want to be able to have the airstream facing down and only going left and right. I was nog able to figure this out with the command 'service: esphome.mhi_gang_set_vanes'. Can somebody tell me the right number codes for the above service?

without this merge request, you can't do that from the esp. after this merge (or update from my repo), you would be able to set vanes vertical to down, and then configure swing for left/right

**Comment by JoepWi** [comment]
> > For one of my MHI units I want to be able to have the airstream facing down and only going left and right. I was nog able to figure this out with the command 'service: esphome.mhi_gang_set_vanes'. Can somebody tell me the right number codes for the above service?
> 
> without this merge request, you can't do that from the esp. after this merge (or update from my repo), you would be able to set vanes vertical to down, and then configure swing for left/right

I'm not fully understanding your answer. (age and lack of experience with GitHub ;) ).
But I did install your repo which gave me the possibility in HA to set with the standard 'thermostat' the swing mode, but not the possibility to set the airstream down and moving l/r.
And I could not figure out what the codes are for the movement in a script/automation.

But it is maybe possible that my expectations are not in line with the design. ;)

**Comment by RobertJansen1** [comment]
> that my expectations are not in line with the design. ;)

The ESPhome climate doesn't allow for the extensive, fine-grained list of airflow we now get with the MHI, it only has swing vertical, horizontal, both or off. I added additional templates to the esphome yaml, which should end up in your home assistant under your device (settings > devices and services > esphome > devices > your AC) allowing to set the vanes horizontally or vertically.
this are the entities:
      - switch.3d_auto
      - select.fan_control_left_right
      - select.fan_control_up_down

**Comment by JoepWi** [comment]
Ok, I had to abandon this new version as 1 of my 4 units is a floor standing (SRF25ZS-W) and does not work any more with the new code.

**Comment by RobertJansen1** [comment]
> Ok, I had to abandon this new version as 1 of my 4 units is a floor standing (SRF25ZS-W) and does not work any more with the new code.

Interesting, probably this unit doesn't support the 33 byte framesize. i will check if i can implement a variable which you can set for unsupported units. i didn't include this (glsf91 did) this will take some time though
> 
> Edit Extra info: Also the web interface became unavailable for all my units with this new version.
the web server was not part of the esphome code of the original project, and isn't in mine as well. you probably added them yourself with: 

web_server:
  port: 80

which you can do again of course :)

**Comment by JoepWi** [comment]
I added the web acces again. My mistake.

And as a work-around I used the new code for updating my three compatible (hanging) units and did not update the standing one.

And to prevent future mistakes I removed the files used to update the unit: resulting in an error if I by accident use 'update all' in esphome ;)

**Comment by glsf91** [comment]
> Interesting, probably this unit doesn't support the 33 byte framesize.

That is strange because the SRF25ZS-W unit supports a wf-rac module.

**Comment by JoepWi** [comment]
> > Interesting, probably this unit doesn't support the 33 byte framesize.
> 
> 
> 
> That is strange because the SRF25ZS-W unit supports a wf-rac module. 

I'll do some more testing tomorrow and keep you posted.

**Comment by ervee** [comment]
> And as a work-around I used the new code for updating my three compatible (hanging) units and did not update the standing one.
> 
> And to prevent future mistakes I removed the files used to update the unit: resulting in an error if I by accident use 'update all' in esphome ;)

You could have specific versions of the project in separate directories!
To prevent clutter I keep the latest version in an ```includes/mhi/``` directory. You can easily create this through the File Browser plugin. Just navigate to ```/config/esphome``` folder and create a folder like ```includes``` and in there a folder like ```mhi```. Then change the part in the ESPHome yaml to:

```
  includes:
    - includes/mhi/mhi_ac_ctrl.h
    - includes/mhi/MHI-AC-Ctrl-core.h
    - includes/mhi/MHI-AC-Ctrl-core.cpp
```

You could have working/old .h and .cpp files in a mhi-SRF25ZS-W folder and include that in the yaml for the SRF25ZS-W. Then you can still update all you want.

**Comment by RobertJansen1** [comment]
there was a bug in the logic for vane control when switching from swing both to vertical or horizontal. this is now fixed.

**Pull request merged**
